#!/usr/bin/env bash
# LibreHub installer.
# Runs LibreHub from this source tree via wrapper scripts, using the system
# Python (which already provides PyGObject/GTK and evdev). No pip/pipx/venv is
# required — deliberately, because this GTK app needs the *system* PyGObject,
# which pipx/venv isolation would hide.
set -euo pipefail

REPO="$(cd "$(dirname "$0")" && pwd)"
BIN="$HOME/.local/bin"
echo "Installing LibreHub from $REPO ..."

# --- 1. Check system runtime dependencies -----------------------------------
missing=""
python3 -c "import gi; gi.require_version('Gtk','3.0'); from gi.repository import Gtk" 2>/dev/null \
  || missing="$missing python3-gi gir1.2-gtk-3.0"
python3 -c "import evdev" 2>/dev/null || missing="$missing python3-evdev"
command -v ratbagctl >/dev/null 2>&1 || missing="$missing ratbagd"
if [ -n "$missing" ]; then
  echo "Missing system packages:$missing"
  echo "Install them, then re-run this script:"
  echo "  sudo apt install$missing"
  exit 1
fi

# --- 2. Console-script wrappers (run from source, use system packages) -------
mkdir -p "$BIN"
for entry in "gui:librehub" "daemon:librehub-daemon" "tray:librehub-tray" \
             "preflight:librehub-doctor"; do
  mod="${entry%%:*}"; name="${entry##*:}"
  cat > "$BIN/$name" <<EOF
#!/bin/sh
# LibreHub wrapper (generated by install.sh) — runs from source with system Python.
export PYTHONPATH="$REPO\${PYTHONPATH:+:\$PYTHONPATH}"
# Fallback X env for when the daemon is started early by systemd --user (single-seat desktop).
[ -n "\${DISPLAY:-}" ] || export DISPLAY=:0
[ -n "\${XAUTHORITY:-}" ] || { [ -f "\$HOME/.Xauthority" ] && export XAUTHORITY="\$HOME/.Xauthority"; }
exec python3 -m librehub.$mod "\$@"
EOF
  chmod +x "$BIN/$name"
done
echo "Installed wrappers in $BIN: librehub, librehub-daemon, librehub-tray"

# --- 3. Desktop entry (absolute Exec so it works regardless of PATH) ---------
mkdir -p "$HOME/.local/share/applications"
sed "s|^Exec=librehub\$|Exec=$BIN/librehub|" packaging/librehub.desktop \
  > "$HOME/.local/share/applications/librehub.desktop"

# --- 3b. Tray autostart entry (runs in background, no taskbar window) --------
mkdir -p "$HOME/.config/autostart"
sed "s|^Exec=librehub-tray\$|Exec=$BIN/librehub-tray|" packaging/librehub-tray.desktop \
  > "$HOME/.config/autostart/librehub-tray.desktop"

# --- 4. systemd --user service ----------------------------------------------
mkdir -p "$HOME/.config/systemd/user"
install -m 0644 packaging/librehub-daemon.service \
  "$HOME/.config/systemd/user/librehub-daemon.service"
systemctl --user daemon-reload 2>/dev/null || true

# --- 5. Privileged: /dev/uinput + input-group access (one-time) --------------
# The daemon reads the mouse's evdev endpoint and writes to /dev/uinput; both
# require membership in the 'input' group plus a udev rule on /dev/uinput.
need_relogin=0
if [ ! -f /etc/udev/rules.d/99-librehub-uinput.rules ]; then
  echo "Installing udev rule for /dev/uinput (sudo may prompt)..."
  if sudo install -m 0644 packaging/99-librehub-uinput.rules \
        /etc/udev/rules.d/99-librehub-uinput.rules; then
    sudo udevadm control --reload-rules && sudo udevadm trigger || true
  else
    echo "  (skipped — run this later with sudo to enable remapping)"
  fi
fi
if ! id -nG "$USER" | tr ' ' '\n' | grep -qx input; then
  if sudo usermod -aG input "$USER"; then
    echo "Added $USER to the 'input' group."
    need_relogin=1
  else
    echo "  (could not add you to 'input' group — do it with: sudo usermod -aG input $USER)"
  fi
fi

# --- 6. Enable the daemon ----------------------------------------------------
if [ "$need_relogin" -eq 0 ]; then
  systemctl --user enable --now librehub-daemon.service 2>/dev/null \
    || echo "Start the daemon later with: systemctl --user enable --now librehub-daemon.service"
else
  systemctl --user enable librehub-daemon.service 2>/dev/null || true
fi

echo
echo "Done."
[ "$need_relogin" -eq 1 ] && echo "IMPORTANT: log out and back in for 'input' group membership to take effect."
echo "If '~/.local/bin' isn't on your PATH yet, log out/in (Mint adds it when the dir exists)."
echo "Then launch 'LibreHub' from your menu, or run: $BIN/librehub"
